### ISSUE TITLE
Consider making this repository public

### ISSUE THREAD

**Issue by PabRod** [RETURN-project/GEE.aux#3]
GitHub has a limit of free minutes in GitHub actions for private repositories. We just [reached that limit](https://github.com/organizations/RETURN-project/settings/billing/spending_limit). The counter will be restarted on February 1.

For public repositories, none of this is a problem. Is there a reason for this project to be private?

**Comment by wandadk** [comment]
There is no reason to keep it private, so I made the repository public now.
